INSERT INTO series (title, author_id, subgenre_id) VALUES ('Title 1', 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ('Title 2', 1, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 1', 2001, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 2', 2001, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 3', 2001, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 4', 2001, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 5', 2001, 1);
INSERT INTO books (title, year, series_id) VALUES ('Title 6', 2001, 1);
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 1', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 2', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 3', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 4', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 5', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 6', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 7', 'Human', 'Hello');
INSERT INTO characters (series_id, author_id, name, species, motto) VALUES (1, 1, 'Character 8', 'Human', 'Hello');
INSERT INTO subgenres (name) VALUES ('Subgenre 1');
INSERT INTO subgenres (name) VALUES ('Subgenre 2');
INSERT INTO authors (name) VALUES ('Author 1');
INSERT INTO authors (name) VALUES ('Author 2');
INSERT INTO character_books (book_id, character_id) VALUES (1, 1);
INSERT INTO character_books (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books (book_id, character_id) VALUES (3, 1);
INSERT INTO character_books (book_id, character_id) VALUES (4, 1);
INSERT INTO character_books (book_id, character_id) VALUES (5, 1);
INSERT INTO character_books (book_id, character_id) VALUES (6, 1);
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VALUES (2, 2);
INSERT INTO character_books (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books (book_id, character_id) VALUES (4, 2);
INSERT INTO character_books (book_id, character_id) VALUES (5, 2);
INSERT INTO character_books (book_id, character_id) VALUES (6, 2);
INSERT INTO character_books (book_id, character_id) VALUES (1, 3);
INSERT INTO character_books (book_id, character_id) VALUES (2, 3);
INSERT INTO character_books (book_id, character_id) VALUES (3, 3);
INSERT INTO character_books (book_id, character_id) VALUES (4, 3);
